openapi: 3.0.0
info:
  title: Swagger Petstore Cat Team
  license:
    name: MIT
  version: 1.0.9
paths:
  /cat/feed:
    post:
      summary: feed all cats
      tags:
        - cats
        - groom
      responses:
        '200':
          description: successfully groomed the cat
  /cats/pet:
    post:
      summary: pet all the cats
  /pets/{petId}:
    get:
      summary: get the specified pet

